name: Bug report
description: Report a problem or regression in Codea
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out a bug report!
  - type: input
    id: title
    attributes:
      label: Short summary
      description: Clear, concise title of the bug
      placeholder: e.g. Crash when opening project on iPad Pro
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug and what you expected to happen
      placeholder: Tell us what you saw vs expected.
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: Step-by-step instructions to reproduce the behavior
      placeholder: |
        1. Go to ...
        2. Tap on ...
        3. See error
    validations:
      required: true
  - type: textarea
    id: env
    attributes:
      label: Environment
      description: Platform, OS version, Codea version, device model; include logs if relevant
      placeholder: |
        • Platform: iPadOS 18.0
        • Device: iPad Pro 12.9" (M2)
        • Codea: 4.0.x (build ...)
        • Additional context/logs
    validations:
      required: true
  - type: checkboxes
    id: checklists
    attributes:
      label: Checklist
      options:
        - label: I searched existing issues
        - label: I can reproduce this with the latest version
  - type: textarea
    id: extra
    attributes:
      label: Additional context
      description: Screenshots, videos, or sample project
type: Bug
