blank_issues_enabled: false
contact_links:
  - name: Codea community forums
    url: https://talk.codea.io/
    about: Ask questions and discuss ideas with the community.
  - name: Join our Discord
    url: https://discord.gg/NXRDESbCxm
    about: Chat with the team and community in real time.
