name: Feature (internal)
description: Internal – for the Codea development team only
body:
  - type: markdown
    attributes:
      value: |
        ⚠️ Internal only: This template is for the Codea development team. External users should use the Suggestion template.
  - type: textarea
    id: description
    attributes:
      label: Feature description
      description: Describe what this feature covers and why it matters
      placeholder: High-level overview
type: Feature
