name: Enforce org-only Feature template

on:
  issues:
    types: [opened, labeled]

permissions:
  issues: write

jobs:
  enforce:
    runs-on: ubuntu-latest
    steps:
      - name: Enforce org-only for Feature issues
        uses: actions/github-script@v7
        with:
          script: |
            const issue = context.payload.issue;
            if (!issue) return;
            const labels = (issue.labels || []).map(l => typeof l === 'string' ? l : l.name);
            const body = issue.body || '';
            const hasMarker = body.includes('ISSUE-TYPE: feature');
            const isFeature = hasMarker || labels.includes('type: feature') || labels.includes('feature');
            const assoc = issue.author_association || 'NONE';
            const allowed = ['MEMBER', 'OWNER', 'COLLABORATOR']; // adjust if you want to restrict further

            if (isFeature && !allowed.includes(assoc)) {
              const { owner, repo } = context.repo;
              const issue_number = issue.number;
              const notice = [
                'Thanks for the report! The Feature template is reserved for the Codea team.',
                'For public feature ideas, please use the Suggestion template instead.'
              ].join(' ');

              await github.rest.issues.createComment({ owner, repo, issue_number, body: notice });
              try {
                await github.rest.issues.update({ owner, repo, issue_number, state: 'closed', state_reason: 'not_planned' });
              } catch (e) {
                await github.rest.issues.update({ owner, repo, issue_number, state: 'closed' });
              }

              for (const name of ['type: feature', 'feature']) {
                try { await github.rest.issues.removeLabel({ owner, repo, issue_number, name }); } catch {}
              }
            }
