name: Set Issue Type from Template

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  set-type:
    runs-on: ubuntu-latest
    steps:
      - name: Set GitHub Issue Type via GraphQL
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const issue = context.payload.issue;
            if (!issue) return;
            const number = issue.number;
            const body = issue.body || '';

            let desired = null;
            if (body.includes('ISSUE-TYPE: bug')) desired = 'bug';
            else if (body.includes('ISSUE-TYPE: suggestion')) desired = 'suggestion';
            else if (body.includes('ISSUE-TYPE: feature')) desired = 'feature';
            if (!desired) return;

            const data = await github.graphql(`
              query($owner:String!, $repo:String!, $number:Int!) {
                repository(owner:$owner, name:$repo) {
                  issue(number:$number) { id }
                  issueTypes(first: 10) { nodes { id name } }
                }
              }
            `, { owner, repo, number });

            const repoData = data.repository;
            if (!repoData) return;
            const issueId = repoData.issue?.id;
            const typeNode = (repoData.issueTypes?.nodes || []).find(n => n.name && n.name.toLowerCase() === desired);
            if (!issueId || !typeNode) return;

            await github.graphql(`
              mutation($id:ID!, $typeId:ID!) {
                updateIssue(input: { id: $id, issueTypeId: $typeId }) { clientMutationId }
              }
            `, { id: issueId, typeId: typeNode.id });
